### ISSUE TITLE
Comparison with Nuxt.js / VuePress / Peco

### ISSUE THREAD

**Issue by egoist** [egoist/saber#1]
### data-prefetching

In Nuxt.js the data is [pre-fetched at runtime](https://nuxtjs.org/api/pages-fetch/), on both server-side and client-side. While in Saber.js the data is pre-fetched at compile time only, which in most cases is better for static websites.

### simplicity

There's a big list of [options](https://nuxtjs.org/api) in Nuxt.js, it makes sense since Nuxt.js is a versatile framework. But Saber.js is only targeting static websites, this would dramatically decrease the complexity of both maintaining this project and writing actual app code.

### webpack-chain

The webpack config manager that vue-cli 3 and Poi use under the hood.

This doesn't matter that much, Nuxt.js could switch to it too if they want.

### Dynamic routes

In Nuxt.js you use [generate.routes](https://nuxtjs.org/api/configuration-generate#routes) to get actual URLs for dynamic routes like `/user/:id`, but in Saber.js it's done [differently](https://github.com/egoist/saber.js#dynamic-route). 

..etc

## VuePress

Saber.js and VuePress almost works in the same way, (well every Vue static website generator works in the same way), except that Saber.js does not enforce a theme system that VuePress uses, which means Saber.js is better for building application.

### data-prefetching

Not supported for now since VuePress uses local markdown files as source data.

## Peco

[Peco](https://github.com/egojump/peco/tree/master/lib) is something else.. It's like VuePress and Saber.js had a baby. It's more complex and currently in beta. (as a Gatsby.js alternative)

**Comment by JiriChara** [comment]
I was about to ask :trollface:

**Comment by egoist** [comment]
Updated ☝🏻

**Comment by chanlito** [comment]
What about [Ream](https://github.com/ream/ream)?

**Comment by egoist** [comment]
@chanlito similar to Nuxt.js in terms of generating static website.

**Comment by Globerada** [comment]
If I need to fetch fresh data each day, do I have to compile it each day via cron job or something?

**Comment by egoist** [comment]
@Globerada seems you need real-time data, then I think fetching data at compile time would be unnecessary. You can use Nuxt or Ream.

**Comment by egoist** [comment]
This library has been rewritten, currently it's more like Gatsby / Gridsome without graphql.
