### ISSUE TITLE
Host on non-root directory?

### ISSUE THREAD

**Issue by NemoAlex** [egoist/saber#10]
Is there a way to set root URI instead of '/', like the `publicPath` do in Poi?

**Comment by egoist** [comment]
Set `root: '/sub-path/'` in `saber.config.js`, I haven't documented this though 😅

**Comment by NemoAlex** [comment]
Doesn't work I think...

**Comment by egoist** [comment]
which part isn't working?

**Comment by NemoAlex** [comment]
saber.config.js:
```
module.exports = {
  root: '/sub-path/'
}
```

In dev mode,

http://localhost:4000/
```
Cannot GET /
```

http://localhost:4000/sub-path/
```
Cannot GET /sub-path/
```

Do I have to put things into `/pages/sub-path/`?

Saber.js 0.1.10

**Comment by ifyour** [comment]
Same problem.

### saber.config.js
```js
module.exports = {
  root: './'
}
```

### demo
But it not work. https://ifyour.github.io/text-formatter/demo/ , you can visite [this repo](https://github.com/ifyour/text-formatter) :bug: 

### version
saber.js 0.1.6

**Comment by egoist** [comment]
Closing this since the old version is no longer maintained, I'll implement this in 0.3 https://github.com/egoist/saber/projects/1#card-16710493
