### ISSUE TITLE
saber 0.4.8 doesn't load plugins' options

### ISSUE THREAD

**Issue by h404bi** [egoist/saber#127]
- [x] I confirm that this is an issue rather than a question.

#### Version

0.4.8

#### Steps to reproduce

repo: https://github.com/h404bi/www.h404bi.com

#### What is expected?

plugin-generate-feed: Generating feeds as expected.
plugin-query-posts: pagination as expected.

#### What is actually happening?

plugin-generate-feed: doesn't generate feeds.
plugin-query-posts: pagination does not work.

#### Other relevant information

- Result of running `saber -v`: `cli.js/0.4.8 win32-x64 node-v10.15.3`
- Browser version (optional):
- Is Saber a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled?

Downgrading to 0.4.7 works though.

**Comment by egoist** [comment]
Please provide a minimal repo with only affected plugins, probably it's related to windows cause it's working fine on mac, btw you can use `--verbose` flag to see if the plugins get called.
