### ISSUE TITLE
Are we able to use <router-view />?

### ISSUE THREAD

**Issue by designcourse** [egoist/saber#14]
I would like the different routes to be setup within a router-view in the /pages/index.vue component. I created a new Vue project with the vue-cli with the vue router added. 

For instance:
`   
   <template>
      <div>Welcome to saber.js
          <router-link to="/about">About</router-link>

          <p>Lorem ipsum dolor</p>

          <router-view />
       </div>
    </template>
`

When "About" is clicked, it doesn't show the about.vue component in that area of the template -- "Welcome to sabjer.js" the about link and paragraph are lost. 

Is it possible to nest these components in a specific area of the template?  

Thanks..

**Comment by egoist** [comment]
Sure it's supported, can you provide a minimal repo?

**Comment by designcourse** [comment]
I run a large yt channel (youtube.com/user/designcourse with 192k+ subs) and I want to cover Saber.js.  It should bring you a lot of activity.  

Do me a favor and hit me up on Skype (or another messaging platform if you prefer or don't have Skype, just let me know).. My nick on Skype is 'dreamache'

It will be easier for me that way.
