### ISSUE TITLE
Related posts support

### ISSUE THREAD

**Issue by iCyris** [egoist/saber#28]
Hello @egoist,

Recently I'm making a theme based on saber, and I want to add related posts function to post pages (e.g. next post, pre post). I didn't find it on the docs, will Saber.js support it in the future? :D

**Comment by egoist** [comment]
I just implemented this in my own blog: https://github.com/egoist/blog/commit/96cb2020e1afc0af15070dd93e0093465a2fe2b4

The latest version of Saber supports saber-node.js in theme directory: https://github.com/egoist/blog/blob/96cb2020e1afc0af15070dd93e0093465a2fe2b4/themes/luna/saber-node.js 

Some APIs are not yet documented though.

**Comment by iCyris** [comment]
It works fine, thank u!
