### ISSUE TITLE
Parse permalinks placeholders from markdown files name

### ISSUE THREAD

**Issue by h404bi** [egoist/saber#31]
Just like what Hexo does.

**saber-config.yml**
```yaml
permalinks:
  post: /posts/:year/:month/:day/:slug.html
```

**./pages/_posts/2019-03-24-hello-saber.md**
```markdown
---
layout: post
date: 2019-03-24
---
```

Expect:

`./pages/_posts/2019-03-24-hello-saber.md` becomes `/posts/2019/03/24/hello-saber.html`

Actual:

`./pages/_posts/2019-03-24-hello-saber.md` becomes `/posts/2019/03/24/2019-03-24-hello-saber.html`

**Comment by egoist** [comment]
Nice we just need to extract the date from filename and use it as the default value of `page.attributes.createdAt` 👌

**Comment by h404bi** [comment]
Proposal:

A new saber config property: `postName` with default value: `:title.md`. The `:slug` of a post defaults to `:title` from `postName`.

When users define `postName` to `:year-:month-:day-:title.md`, extract date `:year-:month-:day` from `postName` as `attributes.createdAt`, and `:title` as`:slug`.

Similar to Hexo: https://github.com/hexojs/hexo/blob/087b3fa456aa97279df61a7f05e59c932051ee2b/lib/plugins/processor/post.js#L49-L54

**Comment by h404bi** [comment]
Another way is making a common page filename format with a built-in regex, inspired by [zola](https://github.com/getzola/zola/blob/eccb1e9986475736381a0d0956cdfd8468f43ba0/components/library/src/content/page.rs#L26).

> Another exception to that rule is that a filename starting with a datetime (YYYY-mm-dd or [a RFC3339 datetime](https://www.ietf.org/rfc/rfc3339.txt)) followed by an underscore (`_`) or a dash (`-`) will use that date as the page date, unless already set in the front-matter. The page name will be anything after `_`/`-` so a filename like `2018-10-10-hello-world.md` will be available at `[base_url]/hello-world`. Note that the full RFC3339 datetime contains colons, which is not a valid character in a filename on Windows. —— [zola doc](https://www.getzola.org/documentation/content/page/)

In this way, no extra `postName` config property needed, page filename format becomes strict but still behaves the same way as Hexo.

**Comment by egoist** [comment]
we have the `permalinks` option https://saberjs.org/docs/permalinks.html#placeholders

**Comment by h404bi** [comment]
Yeah, I know that option. What I want to say is that we need a way to detech whether the filename contains datetime or not, thus I provide two methods to do so. One is customizable and the other is strict. I prefer the latter, and will try to implement it.
