### ISSUE TITLE
feed plugin: support generating atom and rss2 type of feed

### ISSUE THREAD

**Issue by h404bi** [egoist/saber#36]

**Comment by egoist** [comment]
Why do you need that? I think JSON format is already widely supported.

**Comment by h404bi** [comment]
Old websites want the backwards compatibility for subscribers. For example, my website was using atom feed previously, and I want subscribers still can get feeds from my site after I moving my website to SaberJS. Changing feed URL or format without notice would make RSS readers such as Inoreader or Feedly unhappy.

JSON format is great, but some old sites might need a period of transition, to notify all subscribers. It would be better if user can choose the feed format.

**Comment by egoist** [comment]
that makes sense then, PR welcome, a plugin option `format: 'atom' | 'rss' | 'json'` would work.

**Comment by egoist** [comment]
Supported in `saber-plugin-generate-feed@0.1.0`
