### ISSUE TITLE
script tags appear to break HMR/Hot Reloading when included in md file?

### ISSUE THREAD

**Issue by GastroGeek** [egoist/saber#54]
# What
Inserting script tags into an md file seems to break HMR*

# Expected
HMR should work and pages should update without manual refresh

# Reality
HMR does not work and pages do not auto-update.

# Replicating

Create a page with:

```html
# Title

## Subtitles

<script>console.log('I am alive')</script>
```

You will see the console.log message...

Try changing the markdown whilst the script tag remains... it won't update the page. Remove the script tag and HMR kicks in again and things start updating... curiously, if you change the console.log message, that does update the console.log message without refresh... but still not the page 😄 

MBP 15" 2018, Latest macOS, latest Firefox...
Node: 10.14.1
NPM: 6.4.1

*if scripts are to be supported, this needs fixing... else all scripts need removing during compile/build and docs updating so say "no script support" or whatever?

**Comment by egoist** [comment]
the `<script>` tag are treated as Vue SFC `<script>` blocks, and yes it does break [HMR](https://github.com/egoist/saber/blob/master/KNOWN_ISSUES.md#hot-module-replacement-sometimes-doesnt-work).

If you want to use the normal HTML `<script>` tags, use this workaround `<component is="script">console.log('I am alive')</component>`, not sure if this will break HMR though.

**Comment by GastroGeek** [comment]
The appears to work! Thanks for the super quick response 👍

**Comment by egoist** [comment]
SFC `<script>` block in Markdown page should also work with HMR now, try `0.4.2`,
