### ISSUE TITLE
Sidebar doesn't work if you access path without .html

### ISSUE THREAD

**Issue by MarchWorks** [egoist/saber#57]
Try accessing https://saber.land/tutorial/tutorial the sidebar won't work instead an error will show up in the console

**Comment by egoist** [comment]
Yeah because that's how it is generated. we didn't have a route called `/tutorial/tutorial`.

**Comment by h404bi** [comment]
You may redirect https://saber.land/tutorial/tutorial to https://saber.land/tutorial/tutorial.html for user experience and seo purpose.

**Comment by MarchWorks** [comment]
Shouldn't `/tutorial/tutorial` return `404.html` if the route doesn't exist normally, like when you go to ``/tutorial/sssssssss``?

**Comment by egoist** [comment]
@MarchWorks Netlify rewirtes /foo to /foo.html automatically if /foo.html exists.

**Comment by MarchWorks** [comment]
Then should I close this one?

**Comment by egoist** [comment]
@MarchWorks we still need to fix this though, when the *redirect* PR lands.

**Comment by egoist** [comment]
Fixed 👌🏻
