### ISSUE TITLE
Pass route params to async data?

### ISSUE THREAD

**Issue by stursby** [egoist/saber#6]
Is this possible (like in Nuxt), or am I doing it wrong? Trying to accomplish something like this:

```vue
// pages/[id].vue

<template>
  <div>
    <div>Post {{ id }}</div>
    <pre>{{ post }}</pre>
  </div>
</template>

<saber>
import axios from 'axios'

export default {
  params() {
    return {
      id: this.params.id // or this.$route.params.id ??
    }
  },

  async data() {
    const { data: post } = await axios
      .get(`https://jsonplaceholder.typicode.com/posts/${this.$route.params.id}`)
    return {
      post
    }
  }
}
</saber>
```

Getting the following error

![image](https://user-images.githubusercontent.com/527849/40492996-6717e296-5f37-11e8-8a39-e9003187798a.png)

It looks like in the Docs you're providing a hard coded array of params.

**Comment by egoist** [comment]
The `params` method in `<saber>` block is used to get actual URLs. Just like https://nuxtjs.org/api/configuration-generate#routes but here we only need the params part.

**Comment by egoist** [comment]
A potential solution is to allow adding routes programmatically so you won't need dynamic routes:

`saber.node.js`:

```js
export const routes = async () => {
  const posts = await getPosts()
  return posts.map(post => ({
    path: `/post/${post.id}`,
    component: 'components/post.vue'
  }))
}
```

**Comment by egoist** [comment]
@fb-erik currently the data generated by `<saber>` block is directly injected to the component's `data()` method at compile time, so we won't be able to know the exact `params` that's been used at that moment. We can just inject the data for all params to component's `data()` method but that sounds a bit silly 😂

**Comment by fb-erik** [comment]
I see, so the only solution to pre-fetching data for dynamic routes is by using `router.addRoutes` in `saber.app.js` and passing in data using props?

**Comment by samburgers** [comment]
Trying to do a similar thing.. `saber.app.js` doesn't appear to like async OR the below just doesn't appear to work. should it?

`saber.app.js`
```
import axios from "axios";
export default async ({ router }) => {
  const { data } = await axios.get("/sitemap-api");
  const routes = data.map(post => ({
    path: post.url,
    component: `templates/${post.template}`,
    props: { post },
  }));
  router.addRoutes(routes);
};
```

**Comment by egoist** [comment]
@samburgers it does not sound like a good idea to bootstrap the router after a runtime API call, maybe we can pre-evaluate that piece of code at compile time too, like that in `<saber>` block:

```js
import posts from 'saber-preload-loader!./get-posts'
```

```js
// get-posts.js
// runs by a webpack loader
module.exports = () => axios.get('./...').then(res => res.data)
```

**Comment by samburgers** [comment]
what you explained in the below comment is exactly what i need to do... ie hit an API and grab all the routes/urls, and then inside the component have the ability to query the API again for further API calls (post content, related API calls etc)

https://github.com/egoist/saber.js/issues/6#issuecomment-391779007

but adding that to `saber.node.js` appears to have no affect on the build/pages.

**Comment by egoist** [comment]
@samburgers yep that's still a proposal

**Comment by samburgers** [comment]
the `<saber>` tag also seems to introduce some poor developer-experience (breaks editor things like prettier, linters, syntax highlights etc). I would be a big fan of moving everything to `saber.node.js` like your comment above, which would open up further control over multiple content sources too.

**Comment by egoist** [comment]
@samburgers Here's also an alternative experimental, undocumented API to bring `<saber>` block as a `.js` file: https://github.com/egoist/saber.js/blob/master/lib/webpack/saber-js-loader.js

So you can do this in a vue component:

```vue
<script>
import compiled from './getData.saber.js'

export default {
  data() {
    return {...compiled.data}
  }
}
</script>
```

Basically you can write everything that `<saber>` block supported in `.saber.js` too

**Comment by egoist** [comment]
Closing due to rewrite: https://saberjs.org
