### ISSUE TITLE
Plugin for night mode like samsung internet night mode

### ISSUE THREAD

**Issue by MarchWorks** [egoist/saber#65]
#### How should this be implemented in your opinion?
A plugin that generate new style from page style

#### Are you willing to work on this yourself?
Yes

So what do you think about this idea can it be implemented?

**Comment by h404bi** [comment]
Shouldn't it be a theme level feature?

**Comment by egoist** [comment]
Yeah that should depend on the theme.

**Comment by MarchWorks** [comment]
In case a theme doesn't have night mode the developer(user) can use the plugin to generate one

**Comment by MarchWorks** [comment]
But it's true that the developer can just choose a theme with night mode
