### ISSUE TITLE
expose tag/category permalink from query-post plugin

### ISSUE THREAD

**Issue by h404bi** [egoist/saber#69]
## Feature request

Expose/Return the permalink of tags or cateogries from the query-post plugin.

#### What problem does this feature solve?

So users or theme developers can use the permalink in their theme. Currently the only way to do it is by hardcoding the permalink in the theme. For instance:

https://github.com/egoist/blog/blob/b29939c7148e19b32b3020499b27ae29cea0cdf6/themes/luna/layouts/default.vue#L21

However, the permalinks of tags or categories can be dynamically configured by the plugin's option, which means it's independent of the theme. Let's suppose that one user install a compiled theme which contains hardcoded tags/categories support, then the user changes the permalinks format of tags or categories but does not (want to) change the hardcoded permalink format in the compiled theme. Then he/she will encouter problem on routing to tag or category pages.

#### What does the proposed API look like?

First idea comes to my mind is attaching permalink to the tag or category.

#### How should this be implemented in your opinion?

That's so useful if we could access the permalink of a tag/category directly.

```vue
<div class="tags" v-if="tags">
    <saber-link class="tag" :to="`${tag.permalink}`" v-for="tag in tags" :key="tag">
         #{{ tag }}
    </saber-link>
```

#### Are you willing to work on this yourself?

I'm not sure..

**Comment by MarchWorks** [comment]
PR https://github.com/egoist/saber/pull/64
